// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6uhI8pYfSqB688oah-8dGmJ0TKGNHVnQ',
    appId: '1:684159561500:web:417f2177e8f82ea48c54d9',
    messagingSenderId: '684159561500',
    projectId: 'ornamental-app',
    authDomain: 'ornamental-app.firebaseapp.com',
    storageBucket: 'ornamental-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDtA4QVVc7It6WO1iTfEkmy5FtAaDrScE',
    appId: '1:684159561500:android:340ac9b81cfff6b18c54d9',
    messagingSenderId: '684159561500',
    projectId: 'ornamental-app',
    storageBucket: 'ornamental-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX4b6B54dHUMdqhV1_w4jyz_gN46LU2Zs',
    appId: '1:684159561500:ios:0fe20e1460b330168c54d9',
    messagingSenderId: '684159561500',
    projectId: 'ornamental-app',
    storageBucket: 'ornamental-app.appspot.com',
    iosBundleId: 'com.example.ornamental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX4b6B54dHUMdqhV1_w4jyz_gN46LU2Zs',
    appId: '1:684159561500:ios:0fe20e1460b330168c54d9',
    messagingSenderId: '684159561500',
    projectId: 'ornamental-app',
    storageBucket: 'ornamental-app.appspot.com',
    iosBundleId: 'com.example.ornamental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6uhI8pYfSqB688oah-8dGmJ0TKGNHVnQ',
    appId: '1:684159561500:web:ea0f41ec5843e7e18c54d9',
    messagingSenderId: '684159561500',
    projectId: 'ornamental-app',
    authDomain: 'ornamental-app.firebaseapp.com',
    storageBucket: 'ornamental-app.appspot.com',
  );
}
